name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Build App
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run Tests
      env:
        RAILS_ENV: test
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bundle exec rspec

# Based on: https://andycroll.com/ruby/github-actions-ci-for-rails-with-postgresql/
